# Generated by Django 5.1.4 on 2025-04-04 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("helixpress_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="paper",
            name="view_count",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
