# Generated by Django 5.1.4 on 2025-04-04 04:30

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("helixpress_app", "0002_paper_view_count"),
    ]

    operations = [
        migrations.CreateModel(
            name="News",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("title", models.CharField(max_length=200, null=True)),
                ("body", models.TextField(null=True)),
                ("date_created", models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Topic",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("title", models.CharField(max_length=200, null=True)),
                ("deadline", models.DateTimeField(null=True)),
                ("viewed_by", models.PositiveIntegerField(default=0)),
                ("content", models.TextField(null=True)),
                ("keywords", models.CharField(max_length=200, null=True)),
                (
                    "participating_journals",
                    models.ManyToManyField(
                        related_name="topics", to="helixpress_app.journal"
                    ),
                ),
            ],
        ),
    ]
