# Generated by Django 5.1.4 on 2025-04-04 07:44

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("helixpress_app", "0004_role_userprofile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
    ]
