# Generated by Django 5.1.4 on 2025-04-04 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("helixpress_app", "0005_alter_userprofile_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="roles",
        ),
        migrations.AddField(
            model_name="journal",
            name="editors",
            field=models.ManyToManyField(
                blank=True,
                related_name="editor_journals",
                to="helixpress_app.userprofile",
            ),
        ),
        migrations.AddField(
            model_name="journal",
            name="reviewers",
            field=models.ManyToManyField(
                blank=True,
                related_name="reviewer_journals",
                to="helixpress_app.userprofile",
            ),
        ),
    ]
