# Generated by Django 5.1.4 on 2025-04-04 22:16

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("helixpress_app", "0006_remove_userprofile_roles_journal_editors_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="topic",
            name="editors",
            field=models.ManyToManyField(
                blank=True,
                related_name="editor_topics",
                to="helixpress_app.userprofile",
            ),
        ),
        migrations.AlterField(
            model_name="topic",
            name="keywords",
            field=models.TextField(null=True),
        ),
        migrations.CreateModel(
            name="Blog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("title", models.CharField(max_length=200, null=True)),
                ("body", models.TextField(null=True)),
                ("date_created", models.DateTimeField(auto_now_add=True, null=True)),
                (
                    "author",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="helixpress_app.userprofile",
                    ),
                ),
            ],
        ),
    ]
