# Generated by Django 5.1.4 on 2025-04-15 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("helixpress_app", "0007_topic_editors_alter_topic_keywords_blog"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Role",
        ),
    ]
