# Generated by Django 5.1.4 on 2025-04-30 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("helixpress_app", "0008_delete_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="blog",
            name="pic",
            field=models.ImageField(null=True, upload_to="blogs_pics/"),
        ),
        migrations.AddField(
            model_name="issue",
            name="body",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="issue",
            name="title",
            field=models.CharField(max_length=200, null=True),
        ),
    ]
